name: "PyInstaller ManyLinux 2.28 Docker Action"
description: "Run Pyinstaller on ManyLinux 2.28 (x86_64) AlmaLinux 8.7 based using Pyenv"
branding:
  icon: "box"
  color: "green"
inputs:
  pyinstaller-params:
    description: "List of parameters for pyinstaller"
    required: true
runs:
  using: "docker"
  image: "docker://ghcr.io/oleksis/pyinstaller-manylinux:latest"
  args:
    - ${{ fromJSON(inputs.pyinstaller-params) }}
