name: "PyInstaller ManyLinux 2.24 Docker Action"
description: "Run Pyinstaller using ManyLinux 2.24 (x86_64) Debian 9 based"
branding:
  icon: "box"
  color: "green"
inputs:
  pyinstaller-params:
    description: "List of parameters for pyinstaller"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ fromJSON(inputs.pyinstaller-params) }}
